# BEVFormer Camera Calibration Parameters
# 6개 카메라의 내재/외재 파라미터 정의

cameras:
  camera_1:
    # 내재 파라미터 (3x3 행렬)
    intrinsic:
      - [861.727905,    0.0,     969.340548]
      - [   0.0,     860.320827, 514.296749]
      - [0.0, 0.0, 1.0]
    
    # 외재 파라미터 (4x4 변환 행렬: camera -> lidar)
    extrinsic:
      - [ -0.502, -0.485, -0.718, 0.010 ]
      - [  0.865, -0.298, -0.407, 0.460 ]
      - [  0.009,  0.825, -0.565, 1.590 ]
      - [  0.000,  0.000,  0.000, 1.000 ]

  camera_2:
    intrinsic:
      - [861.727905,    0.0,     969.340548]
      - [   0.0,     860.320827, 514.296749]
      - [0.0, 0.0, 1.0]
    extrinsic:
      - [ -0.012,  0.024, -0.999, 0.010 ]
      - [  0.999,  0.016, -0.012, 0.000 ]
      - [ -0.016,  1.000,  0.024, 1.590 ]
      - [  0.000,  0.000,  0.000, 1.000 ]

  camera_3:
    intrinsic:
      - [861.727905,    0.0,     969.340548]
      - [   0.0,     860.320827, 514.296749]
      - [0.0, 0.0, 1.0]
    extrinsic:
      - [ -0.004, -0.004,  1.000, 1.710 ]
      - [ -1.000,  0.004, -0.004, 0.000 ]
      - [  0.004, -1.000, -0.004, 1.400 ]
      - [  0.000,  0.000,  0.000, 1.000 ]

  camera_4:
    intrinsic:
      - [1266.417203046554, 0.0, 816.2670197447984]
      - [0.0, 1266.417203046554, 491.50706579294757]
      - [0.0, 0.0, 1.0]
    extrinsic:
      - [  0.501,  0.506,  0.702,  1.700 ]
      - [  0.865, -0.286, -0.415, -0.450 ]
      - [  0.030, -0.816,  0.578,  1.400 ]
      - [  0.000,  0.000,  0.000,  1.000 ]

  camera_5:
    intrinsic:
      - [861.727905,    0.0,     969.340548]
      - [   0.0,     860.320827, 514.296749]
      - [0.0, 0.0, 1.0]
    extrinsic:
      - [ -0.495,  0.511, -0.702, 0.010 ]
      - [ -0.869, -0.279,  0.410, -0.460 ]
      - [  0.004, -0.815, -0.579,  1.590 ]
      - [  0.000,  0.000,  0.000,  1.000 ]

  camera_6:
    intrinsic:
      - [861.727905,    0.0,     969.340548]
      - [   0.0,     860.320827, 514.296749]
      - [0.0, 0.0, 1.0]
    extrinsic:
      - [  0.497, -0.491,  0.715, 1.700 ]
      - [ -0.868, -0.292,  0.407, 0.450 ]
      - [ -0.001, -0.822, -0.570, 1.400 ]
      - [  0.000,  0.000,  0.000, 1.000 ]

# BEVFormer 관련 설정
bevformer_config:
  # BEV 그리드 설정
  bev_h: 200
  bev_w: 200
  
  # Point cloud range
  pc_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
  
  # 이미지 크기
  img_h: 928
  img_w: 1600
